version: '3'
services:
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - C:/temp/rzp-cockpit/export/allure-reports:/app/default-reports
      - C:/temp/rzp-cockpit/export/allure-results:/app/allure-results